FROM debian:latest

RUN apt-get update && apt-get install -y python3 python3-pip nmap python3-pymodbus

#WORKDIR /opt/csci498
#COPY app.py /opt/csci498/app.py
#RUN cd /opt/csci498/hmi-src && npm install && npm run build && mv build /opt/csci498/hmi
#RUN rm -rf /opt/csci498/hmi-src

#CMD python /opt/csci498/app.py
